### PR TITLE
FEATURE: New crawling methods and speed options

### PR DESCRIPTION
**Pull request by Sebobo**
This change allows not only to crawl a Neos site more efficiently but also store the resulting html somewhere to export a site as static files.

### CODE REVIEW

**Comment by jonnitto** [comment]
What's about Neos 5.0? 😋

**Comment by Sebobo** [comment]
@jonnitto we have to check if it needs adjustments then make a second pr and release another major if necessary.

**Comment by jonnitto** [comment]
Tested it in a real-life project. Very nice. But: On a page with a lot of content to render (high-res images, etc.) it can happen that I got something like `(39/280) Fetch complete for (https://www.domain.tld/path/to/site) - No page title` After that, the crawler can't fetch any page anymore and the server get stressed. Do you wait for a valid status code for every fetch or do you just run over the entries? As a reliable crawler it should wait for a valid status code and if there is a blank answer, give the server some time to rest…

**Comment by Sebobo** [comment]
Thanks for testing!

Interesting. You tested this with the sitemap crawler and not the node crawler correct?

**Comment by Sebobo** [comment]
I never looked deeper into the rolling curl library.
Have to check what can be influenced there and whether we might need a fork or custom implementation of rolling curl.

**Comment by Sebobo** [comment]
Also it would make sense to make it possible to store the curl results too.

**Pull request merged**
